### ISSUE TITLE
Support controlsList in amp-audio Elements

### ISSUE THREAD

**Issue by kennydurkin** [ampproject/amphtml#10803]
## What's the issue?

`<amp-audio>` doesn't currently support controlsList, even though it's a standard attribute. My specific use case is wanting to hide the `<audio>` tags download button via `controlsList="nodownload"`, but this isn't possible right now, leading us to have to use CSS hacks to hide it in the meantime.

MDN doc: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList

```scss
audio::-internal-media-controls-download-button {
    display:none;
}

audio::-webkit-media-controls-enclosure {
    overflow:hidden;
}

audio::-webkit-media-controls-panel {
    width: calc(100% + 35px); /* Adjust as needed */
}
```

Hopefully this wouldn't be too difficult to implement, as I'm assuming `<amp-audio>` would just pass the attribute on to its  `<audio>` child element, which will take it from there.

## What browsers are affected?
Chrome is the only browser that shows the download button. It has supported `controlsList="nodownload"` since Chrome 55.
<img width="278" alt="screen shot 2017-08-04 at 2 35 25 pm" src="https://user-images.githubusercontent.com/5722340/28982034-3a14cdf0-7922-11e7-9c9f-687df15634a6.png">

However, the CSS which hides it will affect Safari HTML5 players as well, which isn't ideal.
<img width="270" alt="screen shot 2017-08-04 at 2 35 36 pm" src="https://user-images.githubusercontent.com/5722340/28982039-403b8408-7922-11e7-960e-9f4c83c3d2aa.png">

## Which AMP version is affected?
The feature doesn't exist yet, so all AMP versions are affected.
