### ISSUE TITLE
Body Scrolling doesn't stop on amp-lightbox on iOS

### ISSUE THREAD

**Issue by bhavyasaggi** [ampproject/amphtml#11225]
If a lengthy page has an amp-lightbox extention in use and the lightbox is active, the scrollbar still shows and background main body could be scrolled while lightbox is in view for iOS devices.

PS: This issue was reported before too and was closed [#6487], but still occurs.

Platforms: Safari (iOS), Opera Mini (Android)

**Comment by aghassemi** [comment]
related: #10623

**Comment by ampprojectbot** [comment]
This issue hasn't been  updated in awhile. @aghassemi Do you have any updates?

**Comment by ampprojectbot** [comment]
This issue hasn't been  updated in awhile. @aghassemi Do you have any updates?

**Comment by xrow** [comment]
Hi,

we noticed the same issue with lastest ios version.

**Comment by jean-felipe** [comment]
Hello, we got the same problem, both `amp-lightbox` and `amp-sidebar`, the body behind still scroll in safari(ios) and opera mini(android), do you have some  update in this case or some workaround?

I notice that when the `amp-lightbox` is open, the `html` receives the class `i-amphtml-scroll-disabled` and its change the html attributes to:
```css
#i-amphtml-wrapper.i-amphtml-scroll-disabled, .i-amphtml-scroll-disabled {
    overflow-x: hidden!important;
    overflow-y: hidden!important;
}
```

But the body, still have the css attributes:
```css
html.i-amphtml-fie>body, html.i-amphtml-singledoc>body {
    overflow: visible!important;
    position: relative!important;
}
```

This can be the cause for this, cause i cannot make my css be "more important", so this make the scroll still happens, can you please help with this?
@aghassemi @muxin
