### ISSUE TITLE
iOS 11 No Longer Requires Scroll Hacks

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#11900]
https://output.jsbin.com/bulacap

This is a light "viewer" iframe, wrapping a standard document. The only styles needed are:

```css
html {
  overflow-x: hidden;
  height: 100%;
  -webkit-overflow-scrolling: touch;
}
body {
  height: 100%;
  overflow-x: hidden;
  margin: 0;
}
```

Additionally, fixed-positions are **much** better than iOS 10. There is some very minor jitter. We might be able to remove the fixed-position transfer.
