### ISSUE TITLE
Positioning of unresolved and unbuilt elements breaks always-top/fixed elements

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#1215]
We have

```css
.-amp-unresolved {
  position: relative !important;
  overflow: hidden !important;
}
```

and

```css
.-amp-notbuilt {
  position: relative !important;
  overflow: hidden !important;
  color: transparent !important;
}
```

Both will break stuff like

```css
amp-analytics {
  position: absolute !important;
}
```

CC @dvoytenko
