### ISSUE TITLE
CSS mask: fails using Safari on ampproject cdn cache due to missing CORS headers

### ISSUE THREAD

**Issue by meistudioli** [ampproject/amphtml#16783]
To whom it may concern:

Please access the following links with browser **safari** (desktop || mobile version).
- [ampproject cdn cache - yahoo mall](https://tw-mall-yahoo-com.cdn.ampproject.org/c/s/tw.mall.yahoo.com/amp/store/jacky5318)
- [ampproject cdn cache - yahoo usedcar](https://tw-usedcar-yahoo-com.cdn.ampproject.org/c/s/tw.usedcar.yahoo.com/amp/item/100372462706)

There will be several image CORS errors occur.
![screenshot](https://blog.lalacube.com/mei/img/amp/cors_error.png) 

That's all because safari ask CSS mask image need to add CORS for [security issue](https://trac.webkit.org/changeset/230006/webkit/). That's why ampproject cdn cache file can't render CSS mask and that will make page layout looks strange.

Paul

**Comment by jpettitt** [comment]
Could be cache bug, could be a Safari bug.  css `mask:` on safari requires CORS headers.  I'm guessing Safai is treating masks the same way browsers treat fonts, whereas Chrome sees masks as images. 

This is the offending line in the example page

```CSS
.mask-orb{
  mask:url('https://s-yimg-com.cdn.ampproject.org/i/s/s.yimg.com/ma/auc/item/icon/mask-orb.svg#mask');
  -webkit-mask:url('https://s-yimg-com.cdn.ampproject.org/i/s/s.yimg.com/ma/auc/item/icon/mask-orb.svg');
}
```
