### ISSUE TITLE
IE11 does not support layout intrinsic for amp-img

### ISSUE THREAD

**Issue by p2er** [ampproject/amphtml#17652]
## What's the issue?

AMP-IMG components do not expand to content size if layout intrinsic is used due to a javascript error.

```
Die Eigenschaft "setAttribute" eines undefinierten oder Nullverweises kann nicht abgerufen werden. [object HTMLUnknownElement]

SCRIPT438: Das Objekt unterstützt die Eigenschaft oder Methode "trimLeft" nicht
validator.js (31,802)
```

Sorry for the german error massages. 

## How do we reproduce the issue?

1. open: https://p2er.github.io/amp-articleslider/image-intrinsic.html#development=1
2. JS error pops up in console showing an unsupported attribute (null or undefined) "setAttribute" was called on [object HTMLUnknownElement]
3.JS error states that object does not support "trimLeft"

## What browsers are affected?

Tested on IE 11.228.17134.0

## Which AMP version is affected?

Powered by AMP HTML – Version 1534872626733

**Comment by jpettitt** [comment]
Apparently this is a known issues withe IE SVG support (https://gist.github.com/larrybotha/7881691)

I don't have an IE11 machine to hand right now. Please try adding this to your CSS and let me know if it fixes it.  

```CSS
/* 2 */
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
  img[src*="svg+xml"] {
    width: 100%; 
  }
}
```
