### ISSUE TITLE
More helpful error about trying to use reserved CSS selectors

### ISSUE THREAD

**Issue by dandv** [ampproject/amphtml#19644]
CSS code like

```css
.i-amphtml-accordion-content {
    padding-left: 50px;
}
```

Will produce [this error](https://github.com/ampproject/amphtml/blob/dd6d65c415bea02f1d149d2ee2d3e22be4071d49/validator/validator-main.protoascii#L5792):

> The text inside tag 'style amp-custom' contains 'CSS i-amphtml- name prefix', which is disallowed.

In the particular case of trying to use reserved CSS selectors, it would be very helpful to point the developer to https://www.ampproject.org/docs/fundamentals/spec#class-and-tag-names.
