### ISSUE TITLE
Consider default `prefers-reduced-motion: reduce` rule

### ISSUE THREAD

**Issue by cramforce** [ampproject/amphtml#20433]
Users can now express that they prefer reduced motion in some user agents.

Should we provide a default in AMP that reduces animations?

```css
@media (prefers-reduced-motion: reduce) {
  * {
    animation: none !important;
    transition: none !important;
  }
}
```

The above would be the biggest hammer and probably not sufficiently compatible. Maybe we can instead reduce the duration to 0, so that all animations are in their end state.

Additionally, transitions and programmatic animations need to also be considered.
