### ISSUE TITLE
How can you show an image overlay once an amp-img has finsihed loading?

### ISSUE THREAD

**Issue by demil** [ampproject/amphtml#22767]
Is there plan to have onload event so we can show overlay with buttons or tags on image in moment when it is loaded? 

Right now only thing is to show overlay before picture is loaded and it is a kind of a unintuitive solution.

Also is there possibility to use image placeholder for all images before image is loaded, not only color but standard image which is prefetched? Is something like theese 2 features in plan?

**Comment by sparhami** [comment]
> Is there plan to have onload event so we can show overlay with buttons or tags on image in moment when it is loaded?

You can do something like the following jsbin: https://jsbin.com/solejo/1/edit?html. Basically, you can use the fact that the placeholder has been hidden to determine when the image is loaded, and then show the overlay at that point. This is done using a following sibling selector `~`:

```css
    .overlay button {
      position: absolute;
      bottom: 0;
      right: 0;
    }
    
    .overlay {
      position: absolute;
      top: 0;
      left: 0;
      bottom: 0;
      right: 0;
      z-index: 1;
      opacity: 0;
      transition: opacity 200ms ease-in;
    }
    
    .amp-hidden[placeholder] ~ .overlay {
      opacity: 1;
    }
```

```html
  <amp-img layout="fixed" width="300" height="200" src="https://ampproject-b5f4c.firebaseapp.com/examples/images/mountains.webp">
    <div placeholder></div>
    <div class="overlay">
      <button>Hello</button>
    </div>
  </amp-img>
```

> Also is there possibility to use image placeholder for all images before image is loaded, not only color but standard image which is prefetched? Is something like theese 2 features in plan?

You should be able to use another image as the `placeholder`. This could be a very low resolution (and thus fast loading) version of the image. This can also be a blurry version of the image that is a very small size. If your image is very small, you can make the `src` a data URI that encodes the image.

/cc @alanorozco
