### ISSUE TITLE
Set some standards in the amp-pinterest extension

### ISSUE THREAD

**Issue by ghost** [ampproject/amphtml#23116]
I find there are quite a few bugs in the amp-pinterest module. I would like to suggest some ideas of fixing them.

## 1. CSS font-size

When testing text in Lighthouse it suggests using `16px` text. I usually set my text to `1rem` instead. With this module it's setting the font-size to 9px in many cases. This is way too small and I can't even read the word 'save'

![1](https://user-images.githubusercontent.com/17784082/60398986-55c55800-9b56-11e9-87d2-f17e5aa90736.png)

Link to demo: https://amp.dev/documentation/examples/components/amp-pinterest/

## 2. Min and Max CSS styling

It seems a bit silly how it's currently set in the code, for example:

```css
.-amp-pinterest-save-button {
    background: url(data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' …-12.975 0-7.167-5.851-12.976-13.068-12.976' fill='%23e60023'/%3E%3C/svg%3E) 3px 5px no-repeat;
    background-size: 10px 10px;
    border-radius: 2px;
    font: 9px/20px Helvetica Neue,Helvetica,sans-serif;
    font-weight: 700;
    max-height: 20px;
    max-width: 40px;
    min-height: 20px;
    min-width: 40px;
    text-indent: 16px;
    text-decoration: none;
    -webkit-font-smoothing: antialiased;
}
```

Here the min and max values of width and height are the exact same. The trouble with doing this is that there is no standard set where you have said we need a certain min size of the icon, for example:

I change the code to fix point one to this:

```css
.-amp-pinterest-save-button {
    background: url(data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' …-12.975 0-7.167-5.851-12.976-13.068-12.976' fill='%23e60023'/%3E%3C/svg%3E) 3px 5px no-repeat;
    background-size: 10px 10px;
    border-radius: 2px;
    font-size: 1rem;
    font-weight: 700;
    max-height: 20px;
    max-width: 40px;
    min-height: 20px;
    min-width: 40px;
    text-indent: 16px;
    text-decoration: none;
    -webkit-font-smoothing: antialiased;
}
```

I added `font-size: 1rem;` by the way. Now it shows the real issue of point two:

![2](https://user-images.githubusercontent.com/17784082/60399056-2400c100-9b57-11e9-8ea8-46688c123d10.png)

To correct this you should set some kind of range for the `min-width` and `max-width` instead of just being lazy and taking the width `size` from the element.

## Final words

Right now I am going to add in the extra code for my website, but this should not be needed and you should fix this extension.

We want it to be like this:

![3](https://user-images.githubusercontent.com/17784082/60399107-cc168a00-9b57-11e9-84cd-78ae66e6b297.png)
