### ISSUE TITLE
Request to remove the !important in amp-consent extension

### ISSUE THREAD

**Issue by ayumihamsaki** [ampproject/amphtml#23117]
I want to create the following:

![3](https://user-images.githubusercontent.com/17784082/60399168-958d3f00-9b58-11e9-9e4c-ba64fc9a33c4.png)

The problem is that the code in the amp-consent is the following:

```css
amp-consent {
    position: fixed;
    bottom: 0;
    left: 0;
    overflow: hidden!important;
    background: hsla(0,0%,100%,0.7);
    width: 100%;
    z-index: 2147483645;
}
```

The issue is the `overflow` line and I want to know why you have decided to set it to `!important` 

To fix the issue I have to add this code:

```css
amp-consent#myUserConsent {
    overflow: initial!important;
}
```

The issue I have is that the validator now flags me for using an `!important`

So I want to open an issue and see if it's really necessary to use `!important` for that line of code.

I have seen no issues what so ever from my code change, so it begs the question of why adding the `!important` to that line in the first place?

Please can you review that line of code, thanks.

p.s. I am fully aware of the amp project adding `!important` to parts of their CSS code. But in this case I don't think you will get any breaking changes with the code.
