### ISSUE TITLE
Use a common sans-serif font family set

### ISSUE THREAD

**Issue by sparhami** [ampproject/amphtml#25888]
AMP currently uses various different `font-family` sets in CSS. For example:

https://github.com/ampproject/amphtml/blob/ccc7a535486e10d13ba919d525c1f3f0e840b4a1/extensions/amp-autocomplete/0.1/amp-autocomplete.css#L21

https://github.com/ampproject/amphtml/blob/ccc7a535486e10d13ba919d525c1f3f0e840b4a1/extensions/amp-list/0.1/amp-list.css#L45

https://github.com/ampproject/amphtml/blob/ccc7a535486e10d13ba919d525c1f3f0e840b4a1/extensions/amp-lightbox/0.1/amp-lightbox.css#L64

https://github.com/ampproject/amphtml/blob/a0f530a190b24ada26cf638b45af9c35680d6518/extensions/amp-date-picker/0.1/amp-date-picker.css#L67

https://github.com/ampproject/amphtml/blob/a0f530a190b24ada26cf638b45af9c35680d6518/extensions/amp-loader/0.1/amp-loader.css#L197

https://github.com/ampproject/amphtml/blob/a0f530a190b24ada26cf638b45af9c35680d6518/extensions/amp-ad/0.1/amp-ad.css#L48

We should consolidate on one uniform set of values, perhaps through a CSS pre-processor or a shared class.

**Comment by sparhami** [comment]
We may also want to do something like the following, to allow page authors to specify what they want the sans-serif font to be across all AMP components:

```css

.foo {
  font-family: var(--amp-sans-serif, Arial, Helvetica, sans-serif);
  font-family: Arial, Helvetica, sans-serif;
}
```

Where `Arial, Helvetica, sans-serif` would be whatever our default set is. We can also just do:

```css

:root {
  --amp-sans-serif: Arial, Helvetica, sans-serif;
}

.foo {
  font-family: var(--amp-sans-serif);
  font-family: sans-serif;
}
```

To simplify the code, such that any browsers not supporting CSS custom properties just gets sans-serif and we have one single font definition (which can be overridden by the page author).
