### ISSUE TITLE
Proposal: create a YAML file for each component that contains the list of events / actions

### ISSUE THREAD

**Issue by fstanis** [ampproject/amphtml#26051]
## Summary

I propose we add a YAML file to each component's folder that'll be used as a "spec" for the actions and events it supports.

For example: `extensions/amp-carousel/amp-carousel.yaml` could be:
```yaml
amp-carousel:
  actions:
    goToSlide:
      parameters:
        index:
          type: INTEGER
          description: slide index to go to
          required: true
      description: Advances the carousel to a specified slide index.
    toggleAutoplay:
      parameters:
        toggleOn:
          type: BOOLEAN
          description: value to toggle to
          required: false
      description: Toggle the carousel's autoplay status.
  events:
    slideChange:
      description: Fired when the carousel's current slide changes.
      data:
        event.index:
          type: INTEGER
          description: index of slide changed to
```

## Reasoning

Currently, all actions and events are documented here: [Actions and Events](https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/?format=websites). However, there are a few issues with this:

- That page has low discoverability. If we used a YAML file as a source of truth, we could also include actions and events on each component page easily.
- That page is also manually maintained and is centralized. Having the YAML file in each component's directory helps mitigate that, similar to how we have validator specs separated.
- Having an easy-to-process actions and events index would allow us to build better tooling and more documentation automation, which is cool.
- AMP for Email only allows a limited subset of actions and we decided in the last WG meeting to standardize it in some form. Having YAML files makes this easier, as we could just have a `formats` field for each action, similar to how the validator has different rules for different formats.

## Corner cases

- Global actions (part of `AMP`) are provided by the runtime. This means no component would have them. Instead, this requires another YAML file for the runtime.
- In additon, there are actions that are not added to any component, but are global: `AMP` and `amp-access`. To handle these, there should be a syntax that indicates the action is on a global object:
```yaml
global:
  AMP:
    actions:
      ...
  amp-carousel:
    actions:
      ...
```
- There are events and actions that apply to all elements. We need a special syntax for this too:
```yaml
"*":
  events:
    tap:
      ...
```
- Some elements that aren't component (e.g. `input`) may have events. In this case, they could either be part of the component YAML for the most relevant component (`amp-form`) or part of the runtime YAML.

## Initial creation

To initially create these YAML files, we could just parse [amp-actions-and-events.md](https://github.com/ampproject/amp.dev/blob/future/pages/content/amp-dev/documentation/guides-and-tutorials/learn/amp-actions-and-events.md).

## Keeping it updated

Ideas welcome. I wonder if there's a way to make a unit test that ensures a YAML line is in line with what the component provides?

//cc @sebastianbenz
