### ISSUE TITLE
Lower specificity of default story font size

### ISSUE THREAD

**Issue by newmuis** [ampproject/amphtml#27026]
We set a default font size on the `<html>` atribute by selecting `html.i-amphtml-story-standalone`.  We should do this in a way with a lower specificity, so that it's more easily overridden.

It can currently be overridden with something like:

```css
html[⚡]:root, html[amp]:root {
  font-size: 16px;
}
```
