### ISSUE TITLE
Update Top-Level Travis Job with Integration to Maven Central/Sonatype

### ISSUE THREAD

**Issue by GeorgeLuo** [ampproject/amphtml#27093]
We would like to publish a distribution of the Java amp validator jar to Maven Central Repository. As a standalone Travis job, these are the instructions to push to Maven Central:
```
branches:
  only:
  - master
  - stable
language: java
env:
  global:
  - secure: ...
  - secure: ...
  - secure: ...
  - secure: ...
jdk:
- openjdk8
before_install: 
install:
- mvn install -Dgpg.skip=true -P !build-extras -B -V
before_script: 
script: mvn test -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"
after_failure:

```

To do this we need a set of Sonatype credentials (env.global.secure)
this link explains those fields:

https://github.com/osmlab/atlas/wiki/Gradle,-Travis-CI-and-Maven-Central

as:
```
global:
    - # GITHUB_SECRET_TOKEN
    - secure: "XXXXXX"
    - # SONATYPE_USERNAME
    - secure: "XXXXXX"
    - # SONATYPE_PASSWORD
    - secure: "XXXXXX"
    - # GPG_KEY_ID
    - secure: "XXXXXX"
    - # GPG_PASSPHRASE
    - secure: "XXXXXX"
    - GPG_KEY_LOCATION=".travis/secret.gpg"
    - ENCRYPTED_GPG_KEY_LOCATION=".travis/secret.gpg.enc"`

```
The trigger for this build job should be on changes to amphtml/validator/java. Additionally a job should be ran on a PR with changes to this directory to validate the maven tests pass (should not trigger a new publish operation to maven central).

Please let me know if any of these points need clarification or I have misunderstood the process.

@honeybadgerdontcare @rsimha

**Comment by rsimha** [comment]
@rcebulko this was the JAVA validator request I mentioned today. Would you be able to pick this up when time permits?

**Comment by GeorgeLuo** [comment]
I brought this problem space to someone who's done this before. I'll describe the process as I understand it from the beginning. Notably, Sonatype will not be involved in this flow and we would look to publish to bintray.

Add this to the amphtml/validator/java/pom.xml

    <distributionManagement>
        <snapshotRepository>
            <id>bintray-amphtml-validator-repo</id>
            <url>http://dl.bintray.com/amphtml/maven</url>
        </snapshotRepository>
        <repository>
            <id>bintray-amphtml-validator-repo</id>
            <url>https://api.bintray.com/maven/amphtml/maven/tagchowder;publish=1</url>
        </repository>
    </distributionManagement>

amphtml/validator/java/cd/deploy.sh (per my previous message)

```
#!/usr/bin/env bash
if [ "$TRAVIS_BRANCH" == 'master' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
    mvn deploy --settings cd/mvnsettings.xml
fi
```

amphtml/validator/java/cd/mvnsettings.xml (referenced from deploy.sh)

```
<settings>
    <servers>
        <server>
            <id>bintray-amphtml-validator-repo</id>
            <username>${env.BINTRAY_USER}</username>
            <password>${env.BINTRAY_API_KEY}</password>
        </server>
    </servers>
</settings>
```

The travis job shared before contains deprecated information, this is what it would look like with those removed. The Sonatype credentials are no longer needed.

```
branches:
  only:
  - master
  - stable
language: java
env:
  global:
jdk:
- openjdk8
before_install: 
install:
- mvn install -Dgpg.skip=true -P !build-extras -B -V
before_script: 
script: mvn test -P !build-extras -B
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./cd/before-deploy.sh"
- "./cd/deploy.sh"
after_failure: 
```

If all this works, we would end up with something that looks like this:

https://bintray.com/yahoo/maven/tagchowder

@rsimha let me know if this makes sense. The ask here would be a set of credentials to use for the the validator BINTRAY_USER and BINTRAY_API_KEY. So an account would need to be set up on bintray and travis provides those environment variables (let me know if this sounds wrong).

In regards to your questions:

deploy.sh does not time much time, that job essentially wraps a build and upload-like process. So won't go over 2 minutes.

no credentials are needed to run maven tests.
