### ISSUE TITLE
[amp-video] Allow to change the position of the poster.

### ISSUE THREAD

**Issue by edoudou** [ampproject/amphtml#27288]
## What's the issue?

There should be a way to changed the poster position on amp-video.

### More details

I tried to change the poster position (set by default at 0% 0%).
After a few research and questions on Slack, the only solution I found was to set the following css rule, which is not amp compliant.
```css
amp-video i-amphtml-poster{
	background-position: 50% 50%;
}
```
### Solution 

We should have a way to specify background-position on a poster through the amp-video API, or it should inherit from the one from the amp-story
