### ISSUE TITLE
Intent to Implement: Simplified amp-social-share

### ISSUE THREAD

**Issue by mkhatib** [ampproject/amphtml#2900]
## Allow Extra Providers with no config changes
Every time someone wants to add a link to a social network that is not configured they'd have to send a PR request to AMP to add that provider to the configs. Instead we'll introduce a new `data-share-endpoint` attribute to allow users to provide the share endpoint even if the network is not in the builtin configs.

```html
<amp-social-share type=”baidu”
    data-share-endpoint=”https://baidu.cn/share”
    data-param-url=”CANONICAL_URL”>
</amp-social-share>

<amp-social-share type=”whatsapp”
    data-share-endpoint=”whatsapp://send”
    data-param-text=”I thought you might like this article: TITLE - CANONICAL_URL”>
</amp-social-share>
```

## Support for variable substitution
We'll also allow [var substitutions](https://github.com/ampproject/amphtml/blob/master/spec/amp-var-substitutions.md) in the params, for example "TITLE" and “CANONICAL_URL” in the example above would be replaced by the current page title and the canonical url for the AMP document.

## Easier Customization for Styles
There's no need for the user to provide elements inside the main `<amp-social-share>`; no anchor, or span container. Only the `amp-social-share` is needed to render, users can still style that element for custom styling. 

```css
  /* AMP social share extension default styling */
  amp-social-share[type=twitter] {
    background-color: #55acee;
    background-image: url(datauri:svg…);
  }
```

```html
<amp-social-share type="twitter"></amp-social-share>
<amp-social-share type="facebook"></amp-social-share>
```

This also allows us to add some minimal default styling for unknown providers:
```css
amp-social-share {
   background-color: #000;
   background-image: url(default-share-icon.svg);
}
```

The user can override the default styling:
```css
amp-social-share[type=”facebook”] {
   Background-color: red;
   background-image: url(myown-facebook-logo.svg);
}
```

## Configuration Through Data-Attributes
We'll drop support for script+json configuration syntax and instead rely completely on data-attributes for configurations. This is consistent with all other amp-elements (with the exception of `amp-analytics`)

## Support More Layouts
Currently the only supported layout is “fixed” which forces the user to provide width and height on every social share element. 

We'll be adding support for all other layouts: fixed, container, fill, fixed-height and responsive.

cc/ @hkmaly @chrisloftus @gam-phon @jayston @corysimmons @jaygray0919 @niallkennedy @paul-matthews @Aetherpoint @luigi
