### ISSUE TITLE
amp-google-doc-embed fails to display multiple documents

### ISSUE THREAD

**Issue by jaygray0919** [ampproject/amphtml#35238]
### Description

This page is valid: https://afdsi.com/__amp-issues/_google-doc-embed/

It uses `amp-google-doc-embed` to feature PDFs, Google Sheets, and Word (docx) files.

However, only the first instance of `amp-google-doc-embed` works.

All document types work, but only when assigned to the first tab.

Are we doing something wrong, or can only one instance of amp-google-doc-embed be displayed on a page?

### Reproduction Steps

https://afdsi.com/__amp-issues/_google-doc-embed/

### Browser(s) Affected

Chrome, Firefox

**Comment by jaygray0919** [comment]
@rebeccanthomas If you use google chrome developer tools to check status, the active tab will open the target document.
However, as you see, only the first tab opens in normal mode.
That behavior suggests to me that the issue is not severe.
Can this problem be resolved in the short term?
We have an iframe solution but would prefer to use a lighter-weight approach as illustrated in the example.
/jay

**Comment by alanorozco** [comment]
**This issue is unrelated to `<amp-google-doc-embed>`**

The problem is the AMP runtime not understanding that the tab content is displayed via these CSS rules that toggle the tabs themselves (`#content...` are all `section` as well).

```css
section {
  display: none;
  ...
}

#tab1:checked ~ #content1,
#tab2:checked ~ #content2,
#tab3:checked ~ #content3,
#tab4:checked ~ #content4,
#tab5:checked ~ #content5 {
  display: block;
}
```

1. If I place multiple `<amp-google-doc-embed>` on the same tab, they all render fine.
2. If I place any kind of `<amp-*>` element on the second tab, it never renders.

cc @ampproject/wg-performance since this is a runtime issue.
