### ISSUE TITLE
amp-iframe - layout="fixed-height" - Safari Browser Bug?

### ISSUE THREAD

**Issue by Polylike** [ampproject/amphtml#4540]
Hello, i have a special problem with amp-iframe and responsive content. The content of the original page is responsive: https://goo.gl/0RvHmy

When i open this original URL in Android - Chrome - Mobile Phone, everthing looks fine. Same when i open this URL on iPhone or iPad.

Now i use amp-iframe and layout="fixed-height" and load the above URL via iFrame on a AMP Page https://goo.gl/meEejz (please scroll down)

On Android - Chrome - Mobile Phone, everthing looks great and the iFrame Content stays responsive. When i use the chrome toogle device toolbar and simulate a iPhone 5 or 6, eyerthing looks fine.

But when i use a real iPhone or iPad and open https://goo.gl/meEejz , the iframe Content isn't responsive and stays in original size.

A amp-iframe bug or a problem of the original content?

**Comment by jridgewell** [comment]
This is an issue with the way Safari handles iframe sizing. Adding

```css
amp-iframe[layout="fixed-height"] iframe {
  width: 1px;
  /* Already defined through .-amp-fill-content:
    min-width: 100%;
    max-width: 100%;
  */
}
```

is a small hack that will fix Safari's crappy sizing issues.

@dvoytenko: What do you think about adding this to the runtime `-amp-fill-content` style?
