### ISSUE TITLE
retire old/unused vendor prefixes.

### ISSUE THREAD

**Issue by tomByrer** [ampproject/amphtml#6666]
I think it is best practice to retire old & almost never used vendor prefixes.

eg: https://ampbyexample.com/introduction/hello_world/
```css
body {
  -webkit-animation: -amp-start 8s steps(1, end) 0s 1 normal both;
  -moz-animation: -amp-start 8s steps(1, end) 0s 1 normal both;
  -ms-animation: -amp-start 8s steps(1, end) 0s 1 normal both;
  animation: -amp-start 8s steps(1, end) 0s 1 normal both
}
@-webkit-keyframes -amp-start {
  from { visibility: hidden }
  to { visibility: visible }
}
@-moz-keyframes -amp-start {
  from { visibility: hidden }
  to { visibility: visible }
}
@-ms-keyframes -amp-start {
  from { visibility: hidden }
  to { visibility: visible }
}
@-o-keyframes -amp-start {
  from { visibility: hidden }
  to { visibility: visible }
}
@keyframes -amp-start {
  from { visibility: hidden }
  to { visibility: visible }
}
```
Stats: http://caniuse.com/#feat=css-animation

First, `-ms-` & `-moz` can safely be dropped, & I doubt the 0.2% of old Opera users is worth it for new websites.  There is enough old mobile browsers to make `-webkit-` worth the weight IMHO.

Not sure if the best solution is to find/replace the repo leaving only `-webkit-` vendor prefixes there (simpler), or remove all vendor prefixes & suggest/provide/implement tooling like [Autoprefixer](https://autoprefixer.github.io/).
What do you think?
