### ISSUE TITLE
Validator incorrectly flags @keyframe rules

### ISSUE THREAD

**Issue by cantrell** [ampproject/amphtml#842]
The specs seem to indicate that this is legal (@keyframes and opacity):

```css
#title-copy {
    animation-duration: 6s;
    animation-name: fade-in;
}

@keyframes fade-in {
    from { opacity: 0; }
    to { opacity: .75; }
}
```

But the validator throws an error:

`CSS_SYNTAX Invalid rule of type: @keyframes`
